services:
  mongo:
    image: mongo:latest
    command: mongod --quiet --logpath /dev/null
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27018:27017
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8084:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongo

  bc-dev-backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.dev
    env_file: ./backend/.env.docker
    restart: always
    ports:
      - 4002:4002
    depends_on:
      - mongo
    volumes:
      - cdn:/var/www/cdn/bookcars
      - ./backend:/bookcars/backend
      - /bookcars/backend/node_modules
      - backend_logs:/bookcars/backend/logs
    environment:
      - NODE_ENV=development
      - BC_FRONTEND_HOST=${BC_FRONTEND_HOST:-http://localhost:8080/}
      - BC_ADMIN_HOST=${BC_ADMIN_HOST:-http://localhost:3001/}
      - BC_WEBSITE_NAME=MITOS RENT A CAR
      - BC_ADMIN_EMAIL=${BC_ADMIN_EMAIL:-admin@mitos.pe}
      - BC_SMTP_FROM=${BC_SMTP_FROM:-no-reply@mitos.pe}
      - BC_EMAIL_ENABLED=false
      - BC_DEFAULT_LANGUAGE=es
      - BC_TIMEZONE=America/Lima
      - BC_IPINFO_DEFAULT_COUNTRY=PE

  bc-dev-admin:
    build:
      context: .
      dockerfile: ./admin/Dockerfile.dev
    env_file: ./admin/.env.docker
    restart: always
    depends_on:
      - bc-dev-backend
    ports:
      - 3001:3001
    volumes:
      - ./admin:/bookcars/admin
      - /bookcars/admin/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - VITE_BC_WEBSITE_NAME=MITOS RENT A CAR
      - VITE_BC_DEFAULT_LANGUAGE=es

  bc-dev-frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.dev
    env_file: ./frontend/.env.docker
    restart: always
    depends_on:
      - bc-dev-backend
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/bookcars/frontend
      - /bookcars/frontend/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - VITE_PORT=8080
      - VITE_BC_WEBSITE_NAME=MITOS RENT A CAR
      - VITE_BC_DEFAULT_LANGUAGE=es
      - VITE_BC_MAP_LATITUDE=-12.0464
      - VITE_BC_MAP_LONGITUDE=-77.0428
      - VITE_BC_MAP_ZOOM=11

volumes:
  cdn:
  mongodb_data:
  mongodb_config:
  backend_logs:
