#!/usr/bin/env bash

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
output_file="$repo_root/.env.mitos-test"

cleanup() {
  unset access_token webhook_secret fx_rate public_key
}
trap cleanup EXIT

require_test_credential() {
  local name="$1"
  local value="$2"

  if [[ -z "$value" ]]; then
    printf 'Error: %s is required.\n' "$name" >&2
    exit 1
  fi

  if [[ "$value" != TEST-* ]]; then
    printf 'Error: %s must be a Mercado Pago TEST credential (expected TEST- prefix).\n' "$name" >&2
    exit 1
  fi
}

printf 'MitoS — Mercado Pago TEST configuration\n'
printf 'Secrets will not be displayed or passed as command-line arguments.\n\n'

read -r -s -p 'BC_MERCADO_PAGO_ACCESS_TOKEN: ' access_token
printf '\n'
read -r -s -p 'BC_MERCADO_PAGO_WEBHOOK_SECRET: ' webhook_secret
printf '\n'
read -r -p 'BC_MITOS_USD_TO_PAYMENT_CURRENCY_RATE (example: 3.80): ' fx_rate
read -r -s -p 'VITE_BC_MERCADO_PAGO_PUBLIC_KEY: ' public_key
printf '\n'

require_test_credential 'BC_MERCADO_PAGO_ACCESS_TOKEN' "$access_token"
require_test_credential 'VITE_BC_MERCADO_PAGO_PUBLIC_KEY' "$public_key"

if [[ -z "$webhook_secret" ]]; then
  printf 'Error: BC_MERCADO_PAGO_WEBHOOK_SECRET is required.\n' >&2
  exit 1
fi

if ! awk -v rate="$fx_rate" 'BEGIN { exit !(rate ~ /^[0-9]+([.][0-9]+)?$/ && rate + 0 > 0) }'; then
  printf 'Error: BC_MITOS_USD_TO_PAYMENT_CURRENCY_RATE must be a positive decimal number.\n' >&2
  exit 1
fi

for component in backend frontend admin; do
  env_file="$repo_root/$component/.env.docker"
  example_file="$repo_root/$component/.env.docker.example"
  if [[ ! -f "$env_file" ]]; then
    cp "$example_file" "$env_file"
    chmod 600 "$env_file"
    printf 'Created %s/.env.docker from its template.\n' "$component"
  fi
done

umask 077
temp_file="$(mktemp "$repo_root/.env.mitos-test.tmp.XXXXXX")"
cat > "$temp_file" <<EOF
# Generated by scripts/configure-mitos-test-env.sh
# Local TEST credentials only. This file is ignored by Git.
BC_MERCADO_PAGO_ACCESS_TOKEN=$access_token
BC_MERCADO_PAGO_WEBHOOK_SECRET=$webhook_secret
BC_MITOS_USD_TO_PAYMENT_CURRENCY_RATE=$fx_rate
VITE_BC_MERCADO_PAGO_PUBLIC_KEY=$public_key
EOF
mv "$temp_file" "$output_file"
chmod 600 "$output_file"

printf '\nConfiguration written to .env.mitos-test (permissions 600).\n'
printf 'Start MitoS with:\n'
printf '  docker compose --env-file .env.mitos-test -f docker-compose.dev.yml up --build\n'
